version: "3"
services:
  cockpit:
    container_name: cockpit.cms
    build: ./.cockpit-build
    ports:
      - 8080:80
    volumes:
      - ./storage:/var/www/html/storage
      - ./config:/var/www/html/config
    restart: always
    tty: true
    networks:
      static-network:
        ipv4_address: 172.20.65.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16